1. install_error.txt  - [Resolved] I have resolved all the VTK related errors by adding python-vtk python-progressbar     in installer.sh script   These python libraries are used by Bemio. These cases needs to be documentated     for Windows and Mac too.
2A: Type Error: [Half done] I have resolved most of the issues, with new VTK library getting enabled, I am getting a varierty
    of new errors in GDFtoDAT converter. I have resolved it in 1-10. Tests (5,5a and 11-25) needs attention for following errors

	IndexError: list index out of range
        ValueError: could not convert string to float:
	IndexError: index 7 is out of bounds for axis 1 with size 6
	could not convert string to float: (end)

2B: Resolved ! - I have made changes in Test2/outtohdf5.py file and installer.sh to resolve it

2C: Resolved ! - I have made changes in Testscript_1.sh to resolve it, currently I am skipping to another Test if there is
                 any exception/error by commenting  set -e in testscript_1, This should be reliable.

3A: this error is not coming in between output db.hdf5 file. Need spike on this.

3B: Resolved !

Deployment Guide : Resolved